name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull latest code in /var/www/html/LoginBE
      run: |
        cd /var/www/html/LoginBE
        git pull origin main
