name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Test SSH Connection
        run: |
          echo "
          spawn ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST}
          expect \"password:\"
          send \"${SSH_PASSWORD}\r\"
          expect \"\\$ \"
          send \"echo 'SSH Connection Successful'\r\"
          expect \"\\$ \"
          send \"exit\r\"
          " > test_ssh.expect
          
          # Chạy script expect để kiểm tra kết nối SSH
          /usr/bin/expect test_ssh.expect
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
