name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Deploy to VM
        run: |
          # Tạo một script expect để tự động nhập mật khẩu
          echo "
          spawn ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST}
          expect \"password:\"
          send \"${SSH_PASSWORD}\r\"
          expect \"$ \"
          send \"cd /var/www/html/LoginBE && git pull origin main && npm install && npm run build && pm2 restart your-app-name\r\"
          expect \"$ \"
          send \"exit\r\"
          " > deploy.expect
          
          # Chạy script expect
          expect deploy.expect
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}