name: laravel 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
       - name: Check runner IP
      run: curl ifconfig.me  
    - name: Check SSH connection
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        HOST: ${{ secrets.SERVER_IP }}
        USER: ${{ secrets.SERVER_USER }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -vvv -o StrictHostKeyChecking=no $USER@$HOST 'echo "SSH connection successful"'

