name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Connect to VM and Pull Code
      run: |
          --script "cd /var/www/html/LoginBE && git pull origin main"
