name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Deploy to VM
        run: |
          # Tạo một script expect để tự động nhập mật khẩu và thực thi lệnh
          echo "
          spawn ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST}
          expect \"password:\"
          send \"${SSH_PASSWORD}\r\"
          expect \"\\$ \"
          send \"cd /var/www/html/LoginBE\r\"
          expect \"\\$ \"
          send \"git status > git_status_before.log 2>&1\r\"
          expect \"\\$ \"
          send \"git pull origin main > git_pull.log 2>&1\r\"
          expect \"\\$ \"
          send \"git status > git_status_after.log 2>&1\r\"
          expect \"\\$ \"
          send \"sudo chown -R www-data:www-data /var/www/html/LoginBE/storage /var/www/html/LoginBE/bootstrap/cache\r\"
          expect \"\\$ \"
          send \"sudo chmod -R 775 /var/www/html/LoginBE/storage /var/www/html/LoginBE/bootstrap/cache\r\"
          expect \"\\$ \"
          send \"sudo systemctl restart nginx > nginx_restart.log 2>&1\r\"
          expect \"\\$ \"
          send \"cat /var/www/html/LoginBE/git_status_before.log\r\"
          expect \"\\$ \"
          send \"cat /var/www/html/LoginBE/git_pull.log\r\"
          expect \"\\$ \"
          send \"cat /var/www/html/LoginBE/git_status_after.log\r\"
          expect \"\\$ \"
          send \"cat /var/www/html/LoginBE/nginx_restart.log\r\"
          expect \"\\$ \"
          send \"exit\r\"
          " > deploy.expect
          
          # Chạy script expect để thực thi lệnh và kiểm tra log
          /usr/bin/expect deploy.expect
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
