name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Deploy to VM
        run: |
          # Tạo một script expect để tự động nhập mật khẩu
          cat << EOF > deploy.expect
          spawn ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
          expect "password:"
          send "${{ secrets.SSH_PASSWORD }}\r"
          expect "\\$ "
          send "echo 'Logged in'; cd /var/www/html/LoginBE && git pull origin main && sudo systemctl restart nginx > deploy.log 2>&1\r"
          expect "\\$ "
          send "echo 'Commands executed'; exit\r"
          EOF
          
          # Chạy script expect
          /usr/bin/expect deploy.expect
          
          # Tạo một script để kiểm tra nhật ký
          cat << EOF > check_log.sh
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cat /var/www/html/LoginBE/deploy.log"
          EOF
          
          # Chạy script kiểm tra nhật ký
          bash check_log.sh
