name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install expect
        run: sudo apt-get install -y expect

      - name: Deploy to VM
        run: |
          # Tạo một script expect để tự động nhập mật khẩu
          echo "
          spawn ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST}
          expect \"password:\"
          send \"${SSH_PASSWORD}\r\"
          expect \"$ \"
          send \"cd /var/www/html/LoginBE\r\"
          expect \"$ \"
          send \"git pull origin main > git_pull.log 2>&1\r\"
          expect \"$ \"
          send \"sudo systemctl restart nginx > nginx_restart.log 2>&1\r\"
          expect \"$ \"
          send \"exit\r\"
          " > deploy.expect
          
          # Chạy script expect
          expect deploy.expect
          
          # Kiểm tra nhật ký git pull
          echo "
          spawn ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST}
          expect \"password:\"
          send \"${SSH_PASSWORD}\r\"
          expect \"$ \"
          send \"cat /var/www/html/LoginBE/git_pull.log\r\"
          expect \"$ \"
          send \"exit\r\"
          " > check_git_log.expect
          
          # Chạy script kiểm tra nhật ký git pull
          expect check_git_log.expect
          
          # Kiểm tra nhật ký nginx restart
          echo "
          spawn ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST}
          expect \"password:\"
          send \"${SSH_PASSWORD}\r\"
          expect \"$ \"
          send \"cat /var/www/html/LoginBE/nginx_restart.log\r\"
          expect \"$ \"
          send \"exit\r\"
          " > check_nginx_log.expect
          
          # Chạy script kiểm tra nhật ký nginx restart
          expect check_nginx_log.expect
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
